version: "3.7"

services:
  db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    ports:
      - 5050:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgres_data:
